apiVersion: isc.ibm.com/v1
kind: ISCSequence
metadata:
  name: tiireports
  labels:
    sort: tiireports
    instance: default
    app.kubernetes.io/name: ibm-isc-tiireports
    helm.sh/chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  labels:
    generation: {{ uuidv4 | quote }}
  dependencies:
     - iscplatform
     - domain-default
  actions:
    - include: tiireports
