apiVersion: isc.ibm.com/v1
kind: ISCSequence
metadata:
  name: csaadapter
  labels:
    sort: csaadapter
    app.kubernetes.io/instance: default
    name: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  labels:
    generation: {{ uuidv4 | quote }}
  dependencies:
     - iscplatform
     - domain-default
  actions:
    - name: creation of APIKey for CSA Adapter
      operation: system-auth
      keyname: csaadapter
    - include: csaadapter     
