apiVersion: v2
appVersion: 1.4.0.0
description: |-
  Data Explorer Service for the CP4S
  Documentation
  Data Explorer Service for Cloud Pak for Security
  License
   "The translated license terms can be viewed here: http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-GBLK-BNGLB3"
home: https://www.ibm.com/security
icon: http://raw.githubusercontent.com/IBM/charts/master/logo/DE.png
keywords:
- amd64
- Commercial
- OCP
- Security
- ICPRHOCP
- RHOCP
- Other
kubeVersion: '>=1.16.0'
maintainers:
- name: IBM
name: isc-dataexplorer-prod
version: 1.0.8
