{{- $imageRepo := (include "image.repository" .) }}
{{- $connector := $.Values.global.images.udiconnector.elasticecs -}}
{{- $image := printf "%s/%s:%s" $imageRepo $connector.image $connector.tag -}}
apiVersion: connector.isc.ibm.com/v1
kind: Connector
metadata:
  name: udi-elastic-ecs
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: "UDI"
  version: {{ .Chart.Version }}
  creator: "IBM"
  image: {{ $image }}
