# Create AuthSvc as an ISCComponent
apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: authsvc
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: authsvc install
    operation: generic-install
    {{- include "platform.annotate" . }}
    {{- include "ibm-isc-platform.podcfg" (dict "val" . "app" "authsvc") }}
    service:
        name: authsvc
        ports:
        - 8443
        - 9443
    jwtKey: true
    env:
      - name: JWT_LIFETIME
        value: "300"
      - name: JWT_ISSUER
        value: '@inventory/platform/definitions/jwt/issuer'
      - name: DB_URL
        value: '@inventory/couch/definitions/url'
      - name: DB_USER
        value: '@secret/couchdb/username'
      - name: DB_KEY
        value: '@secret/couchdb/password'
    liveness_probe:
        path: /ping
    readiness_probe:
        path: /ping
    paths:
    - ingress: /api/introspect
      app: /introspect
      noAuth: true
    sysctls:
      somaxconn: true
