# Deploys CLX-Console, ISC Platform for hosting other teams applications
apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: clxconsole
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: clx-console install
    operation: generic-install
    service:
      name: clx-console
      ports:
        - 3001
    {{- include "platform.annotate" . }}
    {{- include "ibm-isc-platform.podcfg" (dict "val" . "app" "console") }}
    env:
        - name: APP_FQDN
          value: '@inventory/domain/definitions/name'
        - name: APPX_BASE_PATH
          value: '@inventory/platform/definitions/appxbase/url'
        - name: DEMO_MODE
          value: '@inventory/platform/definitions/demomode'
        - name: DEV_MODE
          value: '@inventory/platform/definitions/devmode'
        - name: FLAG_TLS
          value: '@inventory/platform/definitions/featureflags/tls'
        - name: FLAG_PULSE
          value: '@inventory/platform/definitions/featureflags/pulse'
        - name: FLAG_ASK_WATSON
          value: '@inventory/platform/definitions/featureflags/askwatson'
        - name: FLAG_CATALOG
          value: '@inventory/platform/definitions/featureflags/catalog'
        - name: FLAG_CONSOLE_REQUIRES_AUTH
          value: '@inventory/platform/definitions/featureflags/consolerequiresauth'
        - name: FLAG_GETTING_STARTED_ON_PREM
          value: '@inventory/platform/definitions/featureflags/gettingstartedonprem'
        - name: FLAG_STREAM
          value: '@inventory/platform/definitions/featureflags/stream'
        - name: FLAG_XFE
          value: '@inventory/platform/definitions/featureflags/xfe'
        - name: FLAG_INVITE_USER_OCP
          value: '@inventory/platform/definitions/featureflags/inviteuserocp'
        - name: IBM_ID_HOST
          value: '@inventory/platform/definitions/ibmid/host'
        - name: OIDC_SP
          value: '@inventory/platform/definitions/oidc/tenant'
        - name: SIGN_UP_URL
          value: '@inventory/platform/definitions/urxform/url'
        - name: SUPPORT_FORUM_URL
          value: '@inventory/platform/definitions/supportforum/url'
        - name: INVITE_USER_URL
          value: '@inventory/platform/definitions/inviteuser/url'
        - name: PROFILE_SERVICE_HOST
          value: '@inventory/platform/definitions/profileservicehost/url'
        - name: KC_LOCATION
          value: '@inventory/platform/definitions/knowledgecenter/url'
        - name: KC_BASE_PATH
          value: '@inventory/platform/definitions/knowledgecenter/basepath'
        - name: SHELL_HOST
          value: '@inventory/platform/definitions/shellhost/url'
        - name: TII_SEARCH_HOSTNAME
          value: '@inventory/platform/definitions/tiisearchhost/url'
        - name: ENTITLEMENTS_API
          value: '@inventory/platform/definitions/entitlementsapi/url'
    liveness_probe:
        path: /liveness
    readiness_probe:
        path: /readiness
    paths:
        - ingress: /console
          app: /console
          noAuth: true
          timeout: 40000
        - ingress: /
          app: /console/catchall
          noAuth: true
