# Create a couchdb instance for AuthSvc
apiVersion: isc.ibm.com/v1
kind: ISCInventory
metadata:
  name: couchdb-authsvc
  labels:
    sort: couchdb
    instance: authsvc
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  labels:
    sort: couchdb
    instance: authsvc
  references:
    sort: couch
    {{- include "platform.annotate" . }}
    {{- include "ibm-isc-platform.couch_db_instance" (dict "val" .Values "app" "authsvc") }}
  definitions:
    databases:
    - apikeys
  installOptions:
    {{- include "ibm-isc-platform.couch_db_opts" (dict "val" .Values "app" "authsvc") }}
---
