apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: cp4sint
    helm.sh/chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: cp4sint
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/name: ambassador
  sessionAffinity: None
  type: ClusterIP
