# Create Entitlements as an ISCComponent
apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: entitlements
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: entitlements install
    operation: generic-install
    internal_entry: true
    service:
        name: isc-entitlements
        ports:
        - 8443
    {{- include "platform.annotate" . }}
    {{- include "ibm-isc-platform.podcfg" (dict "val" . "app" "entitlements") }}
    env:
    - name: NODE_ENV
      value: "production"
    - name: IAM_API_KEY
      value: '@refsec/connect-idmgmt-apikey/apikey'
    - name: DB_HOSTNAME
      value: '@inventory/couch/definitions/url'
    - name: DB_CLIENT_ID
      value: '@secret/couchdb/username'
    - name: DB_CLIENT_SECRET
      value: '@secret/couchdb/password'
    - name: CLUSTER_URL
      value: '@inventory/platform/definitions/oidc/tenant'
      format: "https://{0}:443"
    - name: INTERNAL_IAM_URL
      value: '@inventory/platform/definitions/iam/url'
    - name: BOM_PATH
      value: "/etc/entitlements/bom.json"
    - name: CLIENT_ID
      value: '@refsec/ibm-isc-oidc-credentials/CLIENT_ID'
    - name: CLIENT_SECRET
      value: '@refsec/ibm-isc-oidc-credentials/CLIENT_SECRET'
    - name: CLUSTER_ADMIN_USERNAME
      value: '@refsec/platform-secret-default/admin'
    - name: CLUSTER_ADMIN_PWD
      value: '@refsec/platform-secret-default/key'
      {{- if $.Values.global.adminUserId }}
    - name: ADMIN_USER_ID
      value: '{{ $.Values.global.adminUserId }}'
      {{- end }}
      {{- if $.Values.global.defaultAccountName }}
    - name: DEFAULT_ACCOUNT_NAME
      value: '{{ $.Values.global.defaultAccountName }}'
      {{- end }}
    configmap_mounts:
    - name: isc-entitlements-bom
      configmap: "isc-entitlements-bom"
      mount_path: "/etc/entitlements"
      optional: true
    - name: isc-entitlements-version
      configmap: "isc-entitlements-version"
      mount_path: "/etc/version"
      optional: true
    init:
    - /bin/bash
    - ./couch_views.sh
    liveness_probe:
      path: /health/v1.0/liveness
    readiness_probe:
      path: /entitlements/v1.0/health/status
    paths:
    - ingress: /api/entitlements/v1.0
      app: /entitlements/v1.0
    - ingress: /api/entitlements/v1.0/entitlements/default
      app: /entitlements/v1.0/entitlements/default
      noAuth: true
    - ingress: /api/entitlements/v1.0/subscriptions
      app: /entitlements/v1.0/subscriptions
      timeout: 30000
    sysctls:
      somaxconn: true
