# Create a default etcd component as an ISCInventory
{{- if not .Values.global.etcd }}
apiVersion: isc.ibm.com/v1
kind: ISCInventory
metadata:
  name: etcd-default
  labels:
    sort: etcd
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  labels:
    sort: etcd
    instance: default
  definitions: 
    name: default
    url: https://ibm-etcd-default-ibm-etcd:2379
    host: ibm-etcd-default-ibm-etcd
    port: 2379
    proto: https
  installOptions:
    enabled: true
    {{- include "ibm-isc-platform.storageDefault" . }}
---
{{- end }}
