# Creating platform as an ISCInventory component
{{- $fqdn := printf "%s.svc.cluster.local" .Release.Namespace }}
apiVersion: isc.ibm.com/v1
kind: ISCInventory
metadata:
  name: iscplatform
  labels:
    sort: platform
    instance: default
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  labels:
    sort: platform
    instance: default
  definitions:
    arch: {{ .Values.global.arch | default "amd64" }}
    affinity: {{ .Values.global.affinity | default "soft" }}
    fasttrack: true
    type: openshift
    replicas: {{ .Values.global.replicas | default 2 }}
    storageClass: {{ required "global.storageClass should be set" .Values.global.storageClass | quote }}
    sys_account: SYSTEM001
    demomode: ""
    devmode: ""
    ideasportal:
      url: "https://ibm-cloud-pak-for-security.ideas.aha.io/"
    inviteuser:
      url: ""
    ibmid:
      host: ""
    appxbase:
      url: ""
    knowledgecenter:
      url: {{ required "global.knowledgecenter.url variable should be set" .Values.global.knowledgecenter.url }}
      basepath: {{ required "global.knowledgecenter.basepath variable is required" .Values.global.knowledgecenter.basepath }}
    supportforum:
      url:  https://www.ibm.com/mysupport/s/topic/0TO0z000000RcPxGAK/cloud-pak-for-security
    walkme:
      url: {{ required "global.walkme.url variable should be set" .Values.global.walkme.url }}
    xforce: https://{{ .Values.global.xforce | default "api.xforce.ibmcloud.com" }}
    xforceweb: https://{{ .Values.global.xforceweb | default "exchange.xforce.ibmcloud.com" }}
    urxform:
      url: ""
    featureflags:
      segment: false
      notifications: false
      editprofile: false
      catalog: false
      consolerequiresauth: true
      pulse: {{ .Values.global.pulse | default "true" }}
      pulse_restricted: {{ .Values.global.pulse_restricted | default "true" }}
      playbooks: {{ .Values.global.cases_playbooks | default "false" }}
      stream: false
      xfe: true
      gettingstartedonprem: true
      askwatson: false
      footerlinks: false
      inviteuserocp: true
    shellappdata:
      apps: ""
    shellhost:
      url: https://clx-shell.{{ $fqdn }}:3002
    profileservicehost:
      url: https://isc-profile.{{ $fqdn }}:3000
    tiisearchhost:
      url: https://tii-search.{{ $fqdn }}:5005
    configstore:
      url: https://cp4sint.{{ $fqdn }}
    iam:
      url: https://icp-management-ingress.{{ $.Values.global.csNamespace }}:443
    cp4sinternal:
      url: https://cp4sint.{{ $fqdn }}
    entitlementsapi:
      url: https://isc-entitlements.{{ $fqdn }}:8443/entitlements/v1.0/entitlements
    oidc:
      {{- $tenant := .Values.global.cluster.icphostname | default (printf "icp-console.apps.%s" .Values.global.cluster.hostname) }}
      {{- if eq $tenant "icp-console.apps." }}
      {{- fail "global.cluster.icphostname or global.cluster.hostname should be set" }}
      {{- end }}
      tenant: {{ $tenant }}
      authorizationurl: https://{{ $tenant }}/idprovider/v1/auth/authorize
      tokenurl: https://icp-management-ingress.{{ $.Values.global.csNamespace }}:443/idprovider/v1/auth/token
      revokeurl: https://icp-management-ingress.{{ $.Values.global.csNamespace }}:443/idprovider/v1/auth/revoke
    pseudotranslation: {{ .Values.global.pseudotranslation | default "" }}
    jwt:
    {{- if .Values.global.jwt }}
      issuer: {{ .Values.global.jwt.issuer | default "isc" }}
    {{- else }}
      issuer: isc
    {{- end }}
    {{- if .Values.global.cluster.hostname }}
    cluster_hostname: {{ .Values.global.cluster.hostname }}
    {{- else }}
    cluster_hostname: {{ $tenant }}
    {{- end }}
    pulse:
      max_concurrent_searches_aql: 50
      search_timeout_aql: 3600
