# The deployment sequence for platform components
apiVersion: isc.ibm.com/v1
kind: ISCSequence
metadata:
  name: iscplatform
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sort: platform
    instance: default
spec:
  labels:
    generation: {{ uuidv4 | quote }}
  dependencies:
     - iscplatform
     - domain-default
  actions: 
    - name: configure couchdb for authsvc
      dependencies:
      - couchdb-authsvc
      operation: couchdb-init
    - include: authsvc
    - name: configure ambassador
      operation: ambassadorcfg
      dependencies:
      - sort=domain
      service:
        name: ambassadorcfg
    - name: configure couchdb for configstore
      dependencies:
      - couchdb-configstore
      operation: couchdb-init
    - include: configstore
      dependencies:  
      - domain-default
    - include: iam-apikey
    - name: configure couchdb for entitlements
      dependencies:
      - couchdb-entitlements
      operation: couchdb-init   
    - include: entitlements
    {{- include "ibm-isc-platform.redis_init" (dict "val" .Values "app" "clxshell") }}
    - name: configure couchdb for clxshell
      dependencies:
      - couchdb-clxregistry
      operation: couchdb-init
    - name: configure console applications
      operation: app-install
    - include: clxshell
    - include: clxconsole
    - name: configure couchdb for pulse
      dependencies:
      - couchdb-pulse
      operation: couchdb-init
    - include: pulsedashboard
