{{- $csns := $.Values.global.csNamespace | default "kube-system" }}
apiVersion: isc.ibm.com/v1
kind: ISCTrust
metadata:
  name: cp4s-default-ca
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  namespace: "{{ $csns }}"
{{- if eq $csns "ibm-common-services" }}
  secret: cs-ca-certificate-secret
  field: tls.crt
{{- else }}
  secret: cluster-ca-cert
  field: tls.crt
{{- end }}
