# Used by the entitlements operator to construct the bill of materials
apiVersion: entitlements.extensions.platform.cp4s.ibm.com/v1
kind: AppEntitlements
metadata:
  name: app-cases
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  applicationId: CaseManagement
  allPermissions:
    - cp4s_role_admin
    - cp4s_role_user
    - edit_all_incidents_fields
    - edit_all_incidents_owner
    - edit_all_incidents_members
    - edit_all_incidents_status
    - delete_all_incidents
    - edit_all_public_tasks
    - edit_all_private_tasks
    - read_all_action_invocations
    - edit_all_incidents_workspaces
    - manage_org_wikis
    - read_all_incidents
    - read_all_private_tasks
    - edit_all_incident_notes
    - edit_all_public_task_notes
    - edit_all_private_task_notes
    - canCreateIncident
    - Authenticated
  roles:
    - roleId: Admin
      permissions:
        - cp4s_role_admin
        - edit_all_incidents_fields
        - edit_all_incidents_owner
        - edit_all_incidents_members
        - edit_all_incidents_status
        - delete_all_incidents
        - edit_all_public_tasks
        - edit_all_private_tasks
        - read_all_action_invocations
        - edit_all_incidents_workspaces
        - manage_org_wikis
        - read_all_incidents
        - read_all_private_tasks
        - edit_all_incident_notes
        - edit_all_public_task_notes
        - edit_all_private_task_notes
        - canCreateIncident
        - Authenticated
    - roleId: User
      permissions: 
        - cp4s_role_user
        - canCreateIncident
        - Authenticated
