{{- if .Values.global.poddisruptionbudget.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "ibm-isc-cases-operator-prod.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "ibm-isc-cases-operator-prod.name" . }}
    helm.sh/chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  minAvailable: {{ .Values.global.poddisruptionbudget.minAvailable }}
  selector:
    matchLabels:
      name: {{ template "ibm-isc-cases-operator-prod.name" . }}
{{- end -}}
