# Create Cluster Role component for Toolbox
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cp4s-toolbox-role
  labels:
    app.kubernetes.io/name: cp4s-toolbox-role
    app.kubernetes.io/instance: ibm-security-solutions
    app.kubernetes.io/managed-by: ibm-security-solutions
rules:
- apiGroups:
  - ""
  resources:
  - pvc
  - pv
  - pods
  - pods/exec
  - services
  - serviceaccounts
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  - batch  
  resources:
  - namespaces
  - nodes  
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - deployments/scale
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - isc.ibm.com
  - entitlements.extensions.platform.cp4s.ibm.com
  - connector.isc.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  - authorization.openshift.io
  attributeRestrictions: null
  resources:
  - rolebindings
  - roles
  verbs:
  - '*'
- apiGroups:
  - logging.openshift.io
  - route.openshift.io
  - certmanager.k8s.io
  - redis.databases.cloud.ibm.com
  - couchdb.databases.cloud.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
