apiVersion: isc.ibm.com/v1
kind: ISCInventory
metadata:
  name: couchdb-tiixfeproxy
  labels:
    sort: couchdb
    instance: tiixfeproxy
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  labels:
    sort: couchdb
    instance: couchdb-tiixfeproxy
  references:
    sort: couch
    {{- include "ibm-isc-tii.couch_db_instance" (dict "val" .Values "app" "tii-xfe-proxy") }}
  definitions:
    databases:
    - tii-xfe
  installOptions:
    {{- include "ibm-isc-tii.couch_db_opts" (dict "val" .Values "app" "tii-xfe-proxy") }}
---
