global:
  bindings:
    tisrfi:
      replicas:
    tisaia:
      replicas:
    tisdatagateway:
      replicas:
    tisscoring:
      replicas:
  repository: ""
  repositoryType: ""
  resources:
    tis:
      tisaia:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1
          memory: 256Mi
      tiscoordinator:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 1
          memory: 128Mi
      tisdatagateway:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 512Mi
      tisrfi:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1
          memory: 256Mi
      tisscoring:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1
          memory: 256Mi
  tisvars:
    recentdays: "14"


# IMAGES:
  images:
    tis:
      tisaia:
        image: isc-tis-aia
        tag: Rel_1.4.0.0_ce28caac6abd9012de101a524458f0194ac34529_2
      tiscoordinator:
        image: isc-tis-coordinator
        tag: Rel_1.4.0.0_52b8bf7ba2eebe8b2ab442efbb3d63fe0bcfa723_22
      tisdatagateway:
        image: isc-tis-data-gateway
        tag: Rel_1.4.0.0_cee7ed9313f82fdd91c52b1109c268f700607dda_21
      tisrfi:
        image: isc-tis-rfi
        tag: Rel_1.4.0.0_eb64cb8dd2bbfd6e3ce96c28f763531efe47c406_20
      tisscoring:
        image: isc-tis-score-controller
        tag: Rel_1.4.0.0_3f661e8b832d94ebe76780517ad8a2aed5733557_19
