apiVersion: v2
appVersion: 1.4.0.0
description: |-
  CR to install connector for UDI and CAR for the CP4S
  Documentation
  CR to install connector for UDI and CAR for the CP4S
  License
   "The translated license terms can be viewed here: http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-GBLK-BNGLB3"
home: https://github.com/IBM/charts/tree/master/entitled/ibm-security-solutions-prod
icon: http://raw.githubusercontent.com/IBM/charts/master/logo/IBM-Security-icon.png
keywords:
- amd64
- Commercial
- OCP
- ICPRHOCP
- Security
- RHOCP
- Other
- Extensions
- Connectors
kubeVersion: '>=1.16.0'
maintainers:
- name: IBM
name: ibm-cp4s-extensions-prod
version: 1.0.8
