apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: tisscoring
  labels:
    app.kubernetes.io/name: ibm-isc-tisscoring
    helm.sh/chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  action:
    name: tisscoring install
    operation: generic-install
    service:
      name: tis-scoring-controller
      proto: https
      ports:
        - 3000
  {{- include "tis.annotations" . }}
  {{- include "ibm-isc-tis.podcfg" (dict "val" . "app" "tisscoring") }}
    env:
      - name: PORT
        value: "3000"
      - name: API_BASE
        value: "/tis/scoring"
      - name: DATA_GATEWAY_URL
        value: "https://tis-data-gateway:3000/tis/gateway"
      - name: CERT_PATH
        value: "/etc/config/ca.crt"
      - name: AUTHBRIDGE_BASE_URL
        value: "https://authsvc:8443"
      - name: XFEPLUS_API_URL
        value: "@inventory/domain/definitions/name"
        format: "https://{0}/app/threat-intelligence-insights/"
    liveness_probe:
      path: /tis/scoring/v2/health/liveness
    readiness_probe:
      path: /tis/scoring/v2/health/readiness
    paths:
      - ingress: /tis/scoring
        app: /tis/scoring
        idle_timeout: 600000
        timeout: 600000
    sysctls:
      somaxconn: true
