apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: aitkwebui
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: aitkwebui install
    operation: generic-install
    env:
        - name: FLAG_TLS
          value: 'True'
    service:
      name: aitk-webui
      ports:
        - 3005
{{- include "aitk.annotate" . }}
{{- include "ibm-isc-platform.podcfg" (dict "val" . "app" "aitkwebui") }}
    liveness_probe:
      path: /app/analytics/liveness
    readiness_probe:
      path: /app/analytics/readiness
    paths:
      - ingress: /app/analytics
        app: /analytics
