{{- range $k,$v := .Values.global.etcd }}
apiVersion: isc.ibm.com/v1
kind: Etcd
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $k }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  name: {{ $k }}
spec:
{{- if $v.installOptions.limits }}
  memory_limit: {{ $v.installOptions.limits.memory | default "600Mi"  }}
  cpu_limit: {{ $v.installOptions.limits.cpu | default "500m"  }}
{{- else }}
  memory_limit: 600Mi
  cpu_limit: 500m
{{- end }}
{{- if $v.installOptions.requests }}
  memory_request: {{ $v.installOptions.requests.memory | default "300Mi"  }}
  cpu_request: {{ $v.installOptions.requests.cpu | default "200m"  }}
{{- else }}
  memory_request: 300Mi
  cpu_request: 200m
{{- end }}
  max_etcd_threads: 2
  replicas: 3
  storage_class_name: {{ $.Values.global.storageClass }}
  storage_size: {{ $v.installOptions.storage | default "1Gi"  }}
  uuid: {{ uuidv4 | quote }}
{{- end }}
