{{ $aitk := .Values.global.aitk | default (dict "none" "none")  }}
apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: orchestrator
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: orchestrator install
    operation: generic-install
    service:
      name: ibm-aitk-orchestrator
      ports:
        - 5000
    env:
    - name: FLAG_TLS
      value: 'True'
    - name: etcd_uri
      value: '@secret/etcd/url'
    - name: redis_port
      value: '@inventory/redis/definitions/port'
    - name: redis_host
      value: '@inventory/redis/definitions/host'
    - name: redis_pass
      value: '@secret/redis/pass'
    - name: redis_sentinel
      value: '@inventory/redis/definitions/sentinel'
    - name: redis_ssl
      value: '@inventory/redis/definitions/ssl'
    - name: release
      value: "Development"
    - name: CERT_KEY_PATH
      value: /etc/config/private.pem
    - name: CERT_PEM_PATH
      value: /etc/config/public.pem
    - name: JWT_SECRET_PATH
      value: /etc/config/jwt.public.pem
    - name: ATK_ACTIVE_JOBS_LIMIT
      value: '{{ $aitk.activeJobsLimit | default "50" }}'
    - name: ANALYTICS_IMAGE_REGISTRY
      value: '@repository'
    - name: ANALYTICS_IMAGE_TAG
      value: '{{ $aitk.analyticsImageTag | default "latest" }}'
    - name: ANALYTICS_NAMESPACE
      value: '{{ .Release.Namespace }}'
    - name: ANALYTICS_IMAGE_PULLSECRET
      value: "ibm-isc-pull-secret"
    - name: ENTITLEMENTS_API
      value: '@inventory/domain/definitions/name'
      format: 'https://{0}/api/entitlements'
    {{- include "aitk.annotate" . }}
    {{- include "ibm-isc-platform.podcfg" ( dict "val" . "app" "orchestrator" "replicas" 1 ) }}
    serviceAccountName: ibm-isc-operators
    tempdir: /tmp
    resources: {}
    containers:
    - name: orchestrator
      ports:
      - 5000
      command:
      - /start.sh
      liveness_probe:
        path: /analytics/v1/health
      readiness_probe:
        path: /analytics/v1/readiness
      {{- include "aitk.resources" ( dict "val" . "app" "orchestrator" ) }}
    - name: celery
      command:
      - /start_celery.sh
      {{- include "aitk.resources" ( dict "val" . "app" "celery" ) }}
    - name: celerybeat
      command:
      - /start_celerybeat.sh
      {{- include "aitk.resources" ( dict "val" . "app" "celerybeat" ) }}
    paths:
      - ingress: /api/analytics/v1
        app: /analytics/v1
