serviceability:
    toolbox:
        _metadata:
          labels: "CP4S Toolbox"
        requests:
          _metadata:
            hidden: true
          cpu:
            _metadata:
              labels: "CPU requests"
              type: "string"
              hidden: true
          memory:
            _metadata:
              labels: "Memory requests"
              type: "string"
              hidden: true
        limits:
          _metadata:
            hidden: true
          cpu:
            _metadata:
              labels: "CPU limits"
              type: "string"
              hidden: true
          memory:
            _metadata:
              labels: "Memory limits"
              type: "string"
              hidden: true
