apiVersion: isc.ibm.com/v1
kind: ISCSequence
metadata:
  name: tiisearch
  labels:
    sort: tiisearch
    instance: default
    app.kubernetes.io/name: ibm-isc-tiisearch
    helm.sh/chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  labels:
    generation: {{ uuidv4 | quote }}
  dependencies:
     - iscplatform
     - domain-default
  actions: 
    - include: tiisearch
