apiVersion: isc.ibm.com/v1
kind: ISCInventory
metadata:
  name: couchdb-de
  labels:
    sort: couchdb
    instance: de
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  labels:
    sort: couchdb
    instance: de
  references:
    sort: couch
    {{- include "ibm-isc-de.couch_db_instance" (dict "val" .Values.global "app" "de") }}
  definitions:
    databases:
    - de-search-records
  installOptions:
    {{- include "ibm-isc-de.couch_db_opts" (dict "val" .Values.global "app" "de") }}
---
