apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: debackend
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: debackend install
    operation: generic-install
    service:
      name: debackend
      proto: https
      ports:
        - 3000
    {{- include "de.annotations" . }}
    {{- include "ibm-isc-de.podcfg" (dict "val" . "app" "backend") }}
    env:
      - name: ENTITLEMENTS_API
        value: '@inventory/domain/definitions/name'
        format: 'https://{0}/api/entitlements'
      - name: UDS_API
        value: '@inventory/domain/definitions/name'
        format: 'https://{0}/api/uds'
      - name: AITK_API
        value: '@inventory/domain/definitions/name'
        format: 'https://{0}/api/analytics'
      - name: AITK_ENABLED
        value: 'enabled'
      - name: SEARCH_RECORDS_DATASTORE_TYPE
        value: 'couchdb'
      - name: SEARCH_RECORDS_COUCH_URL
        value: '@inventory/couch/definitions/url'
      - name: SEARCH_RECORDS_COUCH_USERNAME
        value: '@secret/couchdb/username'
      - name: SEARCH_RECORDS_COUCH_PASSWORD
        value: '@secret/couchdb/password'
      - name: SEARCH_RECORDS_COUCH_DB_NAME
        value: 'de-search-records'
      - name: RESULTS_DATASTORE_TYPE
        value: 'couchdb'
      - name: RESULTS_COUCH_URL
        value: '@inventory/couch/definitions/url'
      - name: RESULTS_COUCH_USERNAME
        value: '@secret/couch/username'
      - name: RESULTS_COUCH_PASSWORD
        value: '@secret/couch/password'
      - name: RESULTS_COUCH_DB_NAME
        value: ''
      - name: REDIS_HOST
        value: '@inventory/redis/definitions/host'
      - name: REDIS_PASS
        value: '@secret/redis/pass'
      - name: REDIS_PORT
        value: '@inventory/redis/definitions/port'
      - name: REDIS_CERT_PATH
        value: "/etc/config"
      - name: REDIS_UNAME
        value: 'admin'
      - name: REDIS_SENTINEL
        value: '@inventory/redis/definitions/sentinel'
      - name: REDIS_CERT_PATH
        value: '/etc/config'  
      - name: REDIS_SENTINEL_NAME
        value: 'mymaster'
      - name: HTTPS_ENABLED
        value: 'true'
      - name: HTTPS_KEY_PATH
        value: '/etc/config/private.pem'
      - name: HTTPS_CERT_PATH
        value: '/etc/config/public.pem'
      - name: HTTPS_CA_PATH
        value: '/etc/config/ca.crt'
      - name: DATABASE_WATCHER_ENABLED
        value: 'true'
      - name: CONSENSUS_REDIS_KEY
        value: de_consensus_redis_key_{{uuidv4}}
      - name: CACHE_REPLACEMENT_DRY_RUN
        value: 'false'
      - name: UDS_PAGE_ASYNC_LIMIT
        value: 300
      - name: GET_UDS_RESULT_DIRECTLY
        value: false
      - name: MINIO_ACCESS_KEY_SECRET
        value: '@refsec/ow-minio-ibm-minio-creds/secretkey'
      - name: MINIO_ACCESS_KEY_ID
        value: '@refsec/ow-minio-ibm-minio-creds/accesskey'
      - name: BUCKET_NAME
        value: 'data-explorer-exports'
      - name: MINIO_PORT
        value: 9000
      - name: MINIO_TIMEOUT
        value: 3000
      - name: MINIO_INTERNAL_URL
        value: ibm-minio-ow-minio-ibm-minio-svc
      - name: MINIO_EXTERNAL_URL
        value: '@inventory/domain/definitions/name'
      - name: MINIO_USESSL
        value: 'false'  
      - name: TIMEOUT_ON_RESULT_QUERY
        value: 5000
      - name: DATASTORE_WATCHER_INTERVAL
        value: 3000
      - name: DATABASE_WATCHER_TOLERANCE_LEVEL
        value: 100
      - name: CACHE_REPLACEMENT_HIGH_DISK_SPACE_WATERMARK
        value: 3000000000
      - name: CACHE_REPLACEMENT_LOW_DISK_SPACE_WATERMARK
        value: 1000000000 
      - name: IS_OCP
        value: true
      - name: MINIO_INTERNAL_PROTOCOL
        value: http://
      - name: MINIO_EXTERNAL_PROTOCOL
        value: https://
      - name: LOG_LEVEL
        value: info
      - name: RESULT_DBS_PURGE_VERSION
        value: v3
    liveness_probe:
      path: /liveness
      scheme: HTTPS
    readiness_probe:
      path: /readiness
      scheme: HTTPS
    paths:
      - ingress: /investigate/api/v1
        app: /investigate/api/v1
        noAuth: false
        timeout: 180000

