apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: dewebui
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: dewebui install
    operation: generic-install
    service:
      name: dewebui
      proto: https
      ports:
      - 3000
    {{- include "de.annotations" . }}
    {{- include "ibm-isc-de.podcfg" (dict "val" . "app" "webui") }}
    env:
      - name: SHELL_HOST
        value: '@inventory/platform/definitions/shellhost/url'
      - name: INVESTIGATE_API
        value: '/investigate/api'
      - name: UDS_API
        value: '/api/uds'
      - name: CAR_API
        value: '/api/car'
      - name: TIS_API
        value: '/tis/rfi/api'
      - name: RESPOND_API
        value: '/api/respond'
      - name: RESPOND_APP_PATH
        value: '/app/respond'
      - name: HTTPS_ENABLED
        value: 'true'
      - name: HTTPS_KEY_PATH
        value: '/etc/config/private.pem'
      - name: HTTPS_CERT_PATH
        value: '/etc/config/public.pem'
      - name: HTTPS_CA_PATH
        value: '/etc/config/ca.crt'
      - name: DEMO_MODE
        value: '@inventory/domain/definitions/demo_mode'
      - name: APP_FQDN
        value: '@inventory/domain/definitions/name'
    liveness_probe:
      path: /liveness
      scheme: HTTPS
    readiness_probe:
      path: /readiness
      scheme: HTTPS
    paths:
      - ingress: /app/data-explorer
        app: /app/data-explorer
        noAuth: true
        timeout: 60000

