apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: minio
      service: "http://ibm-minio-ow-minio-ibm-minio-svc:9000"
      prefix: /data-explorer-exports/
      rewrite: /data-explorer-exports/
      host_rewrite: ibm-minio-ow-minio-ibm-minio-svc:9000
      add_response_headers:
        Strict-Transport-Security: max-age=15552000; includeSubDomains
        X-Frame-Options: SAMEORIGIN
      bypass_auth: true
      timeout_ms: 10000
      host: {{ .Values.global.domain.default.domain}}
  name: de-minio-route
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  sessionAffinity: None
  type: ClusterIP
