
# Declare variables to be passed into your templates.
bindings:
- name: car-connector-config
  debug: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
