apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-isc-car
    app.kubernetes.io/instance: ibm-isc-car
    app.kubernetes.io/managed-by: ibm-isc-car
  name: ibm-cp4s-car-connector-config-cluster-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
    - list
    - get
    - create
    - delete
