apiVersion: isc.ibm.com/v1
kind: ISCSequence
metadata:
  name: car-frontend-ui
  labels:
    sort: car-frontend-ui
    instance: default
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  labels:
    generation: {{ uuidv4 | quote }}
  dependencies:
     - iscplatform
     - domain-default
  actions:
    - include: car-frontend-ui

