{{- $carIngressUrl := $.Values.global.bindings.car.ingressUrl -}}
{{- $fqdn := printf "%s.svc.cluster.local" .Release.Namespace }}

apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: car-connector-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    fsWrite: true
    name: car-connector-config
    operation: generic-install
    serviceAccountName: car-connector-config
    service:
      name: car-connector-config
      ports:
        - 3200
  {{- include "car.annotations" . }}
  {{- include "ibm-isc-car.podcfg" (dict "val" . "app" "carConnectorConfig") }}
    env:
      - name: CAR_API_PATH
        value: {{ $carIngressUrl }}
      - name: APP_FQDN
        value: cp4sint.{{ $fqdn }}
      - name: ENTITLEMENTS_API
        value: '@inventory/domain/definitions/name'
        format: 'https://{0}/api/entitlements/v1.0/entitlements'
      - name: API_KEY_GENERATION_URL
        value: '@inventory/domain/definitions/name'
        format: 'https://{0}/api/apikey/create'
    liveness_probe:
      path: /liveness
    readiness_probe:
      path: /readiness
    paths:
      - ingress: /api/car-connector-config/v1
        app: /api/v1
        noAuth: false
