// Add any tips or answers to anticipated questions. This could include the following troubleshooting information. If you don’t have any other Q&A to add, change “FAQ” to “Troubleshooting.”

== FAQ

*Q.* I encountered a *CREATE_FAILED* error when I launched the Quick Start.

*A.* If AWS CloudFormation fails to create the stack, we recommend that you relaunch the template with *Rollback on failure* set to *Disabled*. (This setting is under *Advanced* in the AWS CloudFormation console, *Options* page.) With this setting, the stack’s state is retained and the instance is left running, so you can troubleshoot the issue. (For Windows, look at the log files in %ProgramFiles%\Amazon\EC2ConfigService and C:\cfn\log.)
// If you’re deploying on Linux instances, provide the location for log files on Linux, or omit this sentence.

WARNING: When you set *Rollback on failure* to *Disabled*, you continue to incur AWS charges for this stack. Please make sure to delete the stack when you finish troubleshooting.

For additional information, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting AWS CloudFormation^] on the AWS website.

*Q.* I encountered a size limitation error when I deployed the AWS CloudFormation templates.

*A.* We recommend that you launch the Quick Start templates from the links in this guide or from another S3 bucket. If you deploy the templates from a local copy on your computer or from a location other than an S3 bucket, you might encounter template size limitations. For more information about AWS CloudFormation quotas, see the http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html[AWS documentation^].


== Troubleshooting
**Where can I get my RedHat pull-secret from?**
Visit: https://cloud.redhat.com/openshift/install/aws/installer-provisioned

**Where can I get my IBM private registry password?**
Visit: https://myibm.ibm.com/products-services/containerlibrary

#### Part 1. Setup resources

**Set-up EC2 Key pair**
From your AWS dashboard (ensure you're in the correct region)
Find Services: EC2 > Network & Security > Key Pairs > Create key pair

**How do I use my key pair to SSH into the BootNode instance?**
When you generate a key pair you should recieve a *\*.pem* file containing the private key. With this you can simply use the *-i* option with *ssh* to login.

```bash
ssh -i path_to_key/key.pem ec2-user@BootNode_instance_ip
```

Where the *path_to_key/key.pem* is where you downloaded your private key and *BootNode_instance_ip* is the public IPv4 address of the BootNode instance.

#### Part 2. Installation of the product

When bootstrapping is complete all depndencies needed to run automation to deploy the desired product should be in place. From here the bootstrap will run the products automation to deploy. First OpenShift is installed using the openshift-install IPI followed by CP4S using in-house built automation.

#### Part 3. Logging

Various log files are generated and it's good to have a reference on where/what they are.

**/ibm/logs/icp4i_install.log** - STDOUT of the openshift-install IPI

**/ibm/logs/icp4i-logs.txt** - STDOUT of the openshift-install IPI

**/ibm/cp4s_install_logs.log** - STDOUT of the CP4S install scripts

#### Part 4. Troubleshooting {partner-product-short-name}

Reference: https://www.ibm.com/support/knowledgecenter/en/SSTDPP_1.4.0/platform/docs/security-pak/troubleshooting.html

Part 4. Logging into the {partner-product-name}

If you are experiencing issues logging into the cosnole for {partner-product-short-name} the most likely error could be incorrect LDAP configuration.

To redeploy the openLDAP and phpLDAPadmin package that comes with this QuickStart simply log onto the EC2 BootNode instance and navigate to the /ibm directory.

You will see a folder called **cp4s-openldap-master** edit the **playbook.yml** file in this directory and redeploy

```bash
ansible-playbook -i hosts playbook.yml
```

If the deployment fails you might need to remove the old LDAP helm deployment before attempting to deploy again

```bash
helm3 delete cp4s-openldap -n default
```

You must have an account named **platform-admin** in the LDAP configuration within the **playbook.yml** file
