// Add any tips or answers to anticipated questions. This could include the following troubleshooting information. If you don’t have any other Q&A to add, change “FAQ” to “Troubleshooting.”

== FAQ

*Q.* Where can I get my Red Hat pull secret?

*A.* Go to the following URL to obtain the pull secret: https://cloud.redhat.com/openshift/install/aws/installer-provisioned.

*Q.* Where can I get my IBM private registry password?

*A.* Go to the following URL to obtain the IBM private registry password: https://myibm.ibm.com/products-services/containerlibrary.

*Q.* I encountered a *CREATE_FAILED* error when I launched the Quick Start.

*A.* If AWS CloudFormation fails to create the stack, relaunch the template with *Rollback on failure* set to *Disabled*. This setting is under *Advanced* in the AWS CloudFormation console on the *Configure stack options* page. With this setting, the stack’s state is retained, and the instance is left running, so you can troubleshoot the issue. (For Windows, look at the log files in %ProgramFiles%\Amazon\EC2ConfigService and C:\cfn\log.)
// If you’re deploying on Linux instances, provide the location for log files on Linux, or omit this sentence.

WARNING: When you set *Rollback on failure* to *Disabled*, you continue to incur AWS charges for this stack. Make sure to delete the stack when you finish troubleshooting.

For additional information, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting AWS CloudFormation^] on the AWS website.

*Q.* I encountered a size limitation error when I deployed the AWS CloudFormation templates.

*A.* Launch the Quick Start templates from the links in this guide or from another S3 bucket. If you deploy the templates from a local copy on your computer or from a location other than an S3 bucket, you might encounter template size limitations. For more information, see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html[AWS CloudFormation quotas^] in the AWS documentation.


== Troubleshooting

=== Installing the product

When bootstrapping is complete, all dependencies that are needed to run automation to deploy the desired product should be in place. From here, the bootstrap will run the product's automation to deploy. First OpenShift is installed using the openshift-install IPI followed by {partner-product-short-name} using automation built in house.

=== Logs

Make notes of the the log files that are generated: 

* /ibm/logs/icp4s_install.log--STDOUT of the openshift-install IPI

* /ibm/cp4s_install_logs.log--STDOUT of the {partner-product-short-name} install scripts

=== Logging in to the {partner-product-short-name} console

If you are experiencing issues logging in to the console for {partner-product-short-name}, the most likely error is an incorrect LDAP configuration.

To redeploy the openLDAP and phpLDAPadmin package that comes with this Quick Start, log in to the EC2 BootNode instance and navigate to the /ibm directory. Edit the *playbook.yml* file in the *cp4s-openldap-master* folder and redeploy: 

```bash
ansible-playbook -i hosts playbook.yml
```

If the deployment fails, you might need to remove the old LDAP helm deployment before attempting to deploy again:

```bash
helm3 delete cp4s-openldap -n default
```

You must have an account named **platform-admin** in the LDAP configuration within the **playbook.yml** file.

For additional troubleshooting, see https://www.ibm.com/support/knowledgecenter/en/SSTDPP_1.4.0/platform/docs/security-pak/troubleshooting.html[Troubleshooting^] in {partner-product-short-name} documentation.
