// If no preperation is required, remove all content from here

==== Prepare your AWS account

Ensure your AWS account has the proper permissions settings to install OpenShift via Installer Provisioned Infrastructure (IPI).

For a list of required permissions, see https://docs.openshift.com/container-platform/4.4/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account[Required AWS permissions^].

This Quick Start creates a new AWS Identity and Access Management (IAM) user with the `AdministratorAccess` policy.

==== Sign up for a Red Hat Subscription

This Quick Start requires a Red Hat subscription. During the deployment of the Quick Start, provide your https://cloud.redhat.com/openshift/install/aws/installer-provisioned[OpenShift Installer Provisioned Infrastructure pull secret^].

If you don’t have a Red Hat account, you can register on the Red Hat website. Note that registration may require a non-personal email address. To get a 60-day evaluation license for OpenShift, see the instructions in https://www.redhat.com/en/technologies/cloud-computing/openshift/try-it[Red Hat OpenShift Container Platform^].

Upload the https://cloud.redhat.com/openshift/install/aws/installer-provisioned[OpenShift pull secret^] to an S3 bucket. The Quick Start pulls this secret file from the specified S3 bucket location to provision the cluster.


==== {partner-product-short-name} Subscription

The Quick Start requires an entitlement key to access the {partner-product-short-name} content.
You can acquire your entitlement key from https://myibm.ibm.com/products-services/containerlibrary[IBM Container Library^].

==== Prepare for the deployment

Confirm that you have a domain name to use for OpenShift in Amazon Route 53: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-register.html[Registering a new domain^].