// If no preperation is required, remove all content from here

==== Prepare your AWS account

Ensure your AWS account has the proper permissions settings to install OpenShift via IPI.

For reference to permissions necessary see: https://docs.openshift.com/container-platform/4.4/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account[Required AWS permissions^].
This Quick Start creates a new IAM user with `AdministratorAccess` policy attached.

==== Sign up for a Red Hat Subscription

This Quick Start requires a Red Hat subscription. During the deployment of the Quick Start, you’ll need to provide your https://cloud.redhat.com/openshift/install/aws/installer-provisioned[OpenShift Installer Provisioned Infrastructure pull secret^].

If you don’t have an Red Hat account, you can register on the Red Hat website. (Note that registration may require a non-personal email address). To procure a 60-day evaluation license for OpenShift, follow the instructions at https://www.redhat.com/en/technologies/cloud-computing/openshift/try-it[Evaluate Red Hat OpenShift Container Platform^].

The https://cloud.redhat.com/openshift/install/aws/installer-provisioned[OpenShift pull secret^] should be uploaded to an S3 bucket. The Quick Start will pull this secret file from the specified S3 bucket location to provision the cluster.


==== {partner-product-short-name} Subscription

The Quick Start requires an entitlement key to allow you to access the {partner-product-short-name} content.
You can acquire your entitlement key from https://myibm.ibm.com/products-services/containerlibrary[IBM Container Library^].

==== Prepare for the deployment

Ensure you have a domain name to use for OpenShift in Amazon Route53: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-register.html[Registering a new domain^].