################################################################################
#
# GLOBAL SETTINGS
#
################################################################################

global:
  __metadata:
    label: "Global Settings"
    description: "Global settings for all components"
  repository:
    __metadata:
        label: "CAR image Repository"
        description: "Docker registry to pull ISC images from"
        type: "string"
        required: true
        hidden: true
  repositoryType:
    __metadata:
      label: "Security-Foundations Image Repository Type"
      description: "Repository type: entitled or local registry"
      type: "string"
      required: true
      hidden: false
      options:
      - label: "Entitled registry"
        value: "entitled"
      - label: "Local registry"
        value: "local"
  imagePullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
      type: "string"
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
  storageClass:
    __metadata:
      label: "Default Storage Class"
      description: "Default storage class for persistence"
      type: "string"
      required: true
  bindings:
    car:
      replicas:
        __metadata:
          label: "replicas for car"
          description: "Number of replicas for car"
          type: "string"
          required: false
      ingressUrl:
        __metadata:
          label: "ingress URL of car service"
          description: "Ingress URL of CAR service"
          type: "string"
          required: true
          hidden: true
    carConnectorConfig:
      replicas:
        __metadata:
          label: "replicas for carConnectorConfig"
          description: "Number of replicas for carConnectorConfig"
          type: "string"
          required: false
    carFrontendUi:
      replicas:
        __metadata:
          label: "replicas for carFrontendUi"
          description: "Number of replicas for carFrontendUi"
          type: "string"
          required: false
  images:
    car:
      car:
        image: 
          __metadata:
            hidden: true
        tag: 
          __metadata:
            hidden: true
      carConnectorConfig:
        image: 
          __metadata:
            hidden: true
        tag: 
          __metadata:
            hidden: true
      carFrontendUi:
        image: 
          __metadata:
            hidden: true
        tag: 
          __metadata:
            hidden: true
    arangodb:
      arangodb: 
        image:
          __metadata:
            label: "ArangoDB image"
            description: "ArangoDB image, e.g. enterprise"
            type: "string"
            required: true
            hidden: true
        tag:
          __metadata:
            label: "ArangoDB image tag"
            description: "ArangoDB image tag, e.g. 3.5.0"
            type: "string"
            required: true
            hidden: true
      exporter: 
        image:
          __metadata:
            label: "ArangoDB exporter image"
            description: "ArangoDB exporter image, i.e. arangodb-exporter"
            type: "string"
            required: true
            hidden: true
        tag:
          __metadata:
            label: "ArangoDB exporter image tag"
            description: "ArangoDB exporter image tag, e.g. 0.1.6"
            type: "string"
            required: true
            hidden: true
  helmTest:
    image:
      __metadata:
        label: "Image name used by helm test"
        description: "The pod image used by helm test"
        type: "string"
        required: false
        hidden: true
    tag:
      __metadata:
        label: "Image tag used by helm test"
        description: "The pod image tag used by helm test"
        type: "string"
        required: false
        hidden: true
  arangodb:
    version:
      __metadata:
        label: "ArangoDB version in this deployment"
        description: "ArangoDB version in this deployment, e.g. 3.6.4"
        type: "string"
        required: true
        hidden: true
    environment:
      __metadata:
        label: "Deployment environment type of ArangoDB"
        description: "Deployment name of ArangoDB, can be either Production or Development"
        type: "string"
        required: true
        hidden: true
    deploymentName:
      __metadata:
        label: "Deployment name of ArangoDB"
        description: "Deployment name of ArangoDB, this value will be used for other components that uses ArangoDB"
        type: "string"
        required: true
        hidden: true
    lifecycle:
      resources:
        requests:
          cpu:
            __metadata:
              label: "CPU requested by ArangoDB deployment lifecycle containers"
              description: "CPU requested by ArangoDB deployment lifecycle containers, e.g 250m"
              type: "string"
              required: false
              hidden: true
          memory:
            __metadata:
              label: "Memory requested by ArangoDB deployment lifecycle containers"
              description: "Memory requested by ArangoDB deployment lifecycle containers, e.g 1Gi"
              type: "string"
              required: false
              hidden: true
        limits:
          cpu:
            __metadata:
              label: "CPU limits of ArangoDB deployment lifecycle containers"
              description: "CPU limits of ArangoDB deployment lifecycle containers, e.g 2"
              type: "string"
              required: false
              hidden: true
          memory:
            __metadata:
              label: "Memory limits of ArangoDB deployment lifecycle containers"
              description: "Memory limits of ArangoDB deployment lifecycle containers, e.g 2Gi"
              type: "string"
              required: false
              hidden: true
    metrics:
      enabled:
        __metadata:
          label: "Flag to enable arangodb metrics"
          description: "If set to true, the arangodb metric (exporters) resources will be added"
          type: "boolean"
          required: false
          hidden: true
      resources:
        requests:
          cpu:
            __metadata:
              label: "CPU requested by ArangoDB deployment metrics"
              description: "CPU requested by ArangoDB deployment metrics, e.g 250m"
              type: "string"
              required: false
              hidden: true
          memory:
            __metadata:
              label: "Memory requested by ArangoDB deployment metrics"
              description: "Memory requested by ArangoDB deployment metrics, e.g 1Gi"
              type: "string"
              required: false
              hidden: true
        limits:
          cpu:
            __metadata:
              label: "CPU limits of ArangoDB deployment metrics"
              description: "CPU limits of ArangoDB deployment metrics, e.g 2"
              type: "string"
              required: false
              hidden: true
          memory:
            __metadata:
              label: "Memory limits of ArangoDB deployment metrics"
              description: "Memory limits of ArangoDB deployment metrics, e.g 2Gi"
              type: "string"
              required: false
              hidden: true
    agentConfiguration:
      probes:
        livenessProbeDisabled:
          __metadata:
            label: "Flag to disable agent liveness probe"
            description: "If set to true, the operator does not generate agent liveness probe"
            type: "boolean"
            required: false
            hidden: true
        readinessProbeDisabled:
          __metadata:
            label: "Flag to disable agent readiness probe"
            description: "If set to true, the operator does not generate agent readiness probe"
            type: "boolean"
            required: false
            hidden: true
      count:
        __metadata:
          label: "Number of ArangoDB deployment agent"
          description: "Number of ArangoDB deployment agent, e.g. 3"
          type: "number"
          required: true
          hidden: false
      args:
        __metadata:
          label: "ArangoDB agent arguments"
          description: "Arguments to control deployment agent"
          type: "string"
          required: true
          hidden: false
      resources:
        requests:
          cpu:
            __metadata:
              label: "CPU requested by ArangoDB deployment agent"
              description: "CPU requested by ArangoDB deployment agent, e.g 250m"
              type: "string"
              required: false
              hidden: false
          memory:
            __metadata:
              label: "Memory requested by ArangoDB deployment agent"
              description: "Memory requested by ArangoDB deployment agent, e.g 1Gi"
              type: "string"
              required: false
              hidden: false
          storage:
            __metadata:
              label: "Storage size of ArangoDB deployment agent"
              description: "Storage size of ArangoDB deployment agent, e.g 100Gi"
              type: "string"
              required: true
              hidden: false
        limits:
          cpu:
            __metadata:
              label: "CPU limits of ArangoDB deployment agent"
              description: "CPU limits of ArangoDB deployment agent, e.g 2"
              type: "string"
              required: false
              hidden: false
          memory:
            __metadata:
              label: "Memory limits of ArangoDB deployment agent"
              description: "Memory limits of ArangoDB deployment agent, e.g 2Gi"
              type: "string"
              required: false
              hidden: false
    singleConfiguration:
      probes:
        livenessProbeDisabled:
          __metadata:
            label: "Flag to disable ArangoDB server liveness probe"
            description: "If set to true, the operator does not generate ArangoDB server liveness probe"
            type: "boolean"
            required: false
            hidden: true
        readinessProbeDisabled:
          __metadata:
            label: "Flag to disable ArangoDB server readiness probe"
            description: "If set to true, the operator does not generate ArangoDB server readiness probe"
            type: "boolean"
            required: false
            hidden: true
      count:
        __metadata:
          label: "ArangoDB server replica count"
          description: "Number of ArangoDB deployment ArangoDB server pod, e.g 2"
          type: "number"
          required: true
          hidden: false
      args:
        __metadata:
          label: "Deployment ArangoDB server arguments"
          description: "Arguments to control deployment ArangoDB servers"
          type: "string"
          required: true
          hidden: false
      resources:
        requests:
          cpu:
            __metadata:
              label: "CPU requested by ArangoDB deployment servers"
              description: "CPU requested by ArangoDB deployment servers, e.g 250m"
              type: "string"
              required: false
              hidden: false
          memory:
            __metadata:
              label: "Memory requested by ArangoDB deployment servers"
              description: "Memory requested by ArangoDB deployment servers, e.g 1Gi"
              type: "string"
              required: false
              hidden: false
          storage:
            __metadata:
              label: "Storage size of ArangoDB deployment servers"
              description: "Storage size of ArangoDB deployment servers, e.g 100Gi"
              type: "string"
              required: true
              hidden: false
        limits:
          cpu:
            __metadata:
              label: "CPU limits of ArangoDB deployment servers"
              description: "CPU limits of ArangoDB deployment servers, e.g 2"
              type: "string"
              required: false
              hidden: false
          memory:
            __metadata:
              label: "Memory limits of ArangoDB deployment servers"
              description: "Memory limits of ArangoDB deployment servers, e.g 2Gi"
              type: "string"
              required: false
              hidden: false
