global:
  bindings:	
    car:
      replicas:
      ingressUrl: '/api/car/v2'
    carConnectorConfig:
      replicas: 1
    carFrontendUi:
      replicas: 1
  
  repository: ""
  repositoryType: ""
  imagePullPolicy: ""
  storageClass: ""

  ## arangodb deployment configuration
  arangodb:
    version: 3.6.5
    environment: Production 
    deploymentName: "arangodb"
    lifecycle:
      resources:
        limits:
          cpu: 75m
          memory: 256Mi
        requests:
          cpu: 12m
          memory: 128Mi
    metrics:
      enabled: false
      resources:
        limits:
          cpu: 75m
          memory: 256Mi
        requests:
          cpu: 12m
          memory: 128Mi
    agentConfiguration:
      probes:
        livenessProbeDisabled: false
        readinessProbeDisabled: false
      count: 3
      args:
        - "--rocksdb.block-cache-size=1073741824"
        - "--cache.size=134217728"
        - "--rocksdb.total-write-buffer-size=1073741824"
        - "--agency.supervision-grace-period=30"
      resources:
        requests:
          storage: 20Gi
          cpu: 30m
          memory: 400Mi
        limits:
          cpu: 240m
          memory: 2500Mi
    singleConfiguration:
      probes:
        livenessProbeDisabled: false
        readinessProbeDisabled: false
      count: 2
      args:
        - "--rocksdb.block-cache-size=1073741824"
        - "--cache.size=134217728"
        - "--rocksdb.total-write-buffer-size=1073741824"
      resources:
        requests:
          storage: 20Gi
          cpu: 15m
          memory: 580Mi
        limits:
          cpu: 600m
          memory: 5Gi
  
  resources:
    car:
      car:
        requests:
          cpu: 60m
          memory: 128Mi
        limits:
          cpu: 600m
          memory: 1Gi
      carConnectorConfig:
        requests:
          cpu: 60m
          memory: 128Mi
        limits:
          cpu: 600m
          memory: 256Mi
# IMAGES:
  images:
    car:
      car:
        image: isc-car
        tag: Rel_1.4.0.0_8314a2b561517252276a9f04a5f380afee62ce52_3020
      carConnectorConfig:
        image: cp4s-car-connector-config
        tag: Rel_1.4.0.0_c83d7b353f98dc0bef68cbf3f3a88785efeba3ba_1268
      carFrontendUi:
        image: cp4s-car-frontend-ui
        tag: Rel_1.4.0.0_1f15b74122de69132944b602b0fe2a65aeb4e70c_1329
    arangodb:
      arangodb:
        image: arangodb-community
        tag: Rel_1.4.0.0_907d25d02bf87f81fcbd080dbf3ad75afb3eed25_2
      exporter:
        image: arangodb-exporter
        tag: Rel_1.4.0.0_907d25d02bf87f81fcbd080dbf3ad75afb3eed25_4
