
global:
  repositoryType: "local"
  arch: amd64
## default number of replicas
  replicas: 2
## default storage class
  storageClass: ""
  jwt:
    issuer:
  csNamespace: ibm-common-services

  cluster:
     hostname: ""

  repository: ""

  domain:
    default:
      domain:

  adminUserId:
  defaultAccountName:

  useDynamicProvisioning: true
  somaxconn: false
  aitk:
    analyticsImageTag: 'Rel_1.4.0.0_a6d87dfd76677319dc7d3dd5a303a092acd24189_57'
    activeJobsLimit: 100
  redis:
    default:
      host:
      port:
      ssl:
      sentinel: false
      installOptions:
        persistence:
        storageClassName:
        storage:
        data:
        server:
          requests:
            memory:
            cpu: 25m
          limits:
            memory:
            cpu: 50m
        sentinel:
          requests:
            memory:
            cpu: 25m
          limits:
            memory:
            cpu: 50m

  couchdb:
      default:
        installOptions:
          version: v3
          storageClass:
          nodes:
          storage: "60Gi"
          requests:
            cpu:
            memory: "256Mi"
          limits:
            cpu:
            memory: "1Gi"
          search:
           limits:
             cpu: 600m
             memory: 3000Mi
           requests:
             cpu: 100m
             memory: 2200Mi

  etcd:
    default:
      host:
      port:
      proto:
      user:
      pass:
      installOptions:
        requests:
          memory: 300Mi
          cpu: 140m
        limits:
          memory: 600Mi
          cpu: 350m
        threads:
        storageClass:
        storageSize:
# OIDC registration configuration
  oidc:
    redirect_uris: []
    post_logout_redirect_uris: []
# Knowledge Center
  knowledgecenter:
    url: "https://www.ibm.com"
    basepath: "/support/knowledgecenter/SSTDPP_1.4.0/platform/docs"
# WALK ME
  walkme:
    url: "https://cdn.walkme.com/users/f7a819249c0546beaf9d1b519b4472ac/walkme_f7a819249c0546beaf9d1b519b4472ac_https.js"
  xforce: "api.xforce.ibmcloud.com"
  xforceweb: "exchange.xforce.ibmcloud.com"

  pseudotranslation: ""

  resources:
    platform:
      iscauth:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi
      iscprofile:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1
          memory: 256Mi
      authsvc:
        requests:
          cpu: 160m
          memory: 128Mi
        limits:
          cpu: 800m
          memory: 256Mi
      shell:
        requests:
          cpu: 100m
          memory: 300Mi
        limits:
          cpu: 1
          memory: 600Mi
      console:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 1
          memory: 400Mi
      qproxy:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 1
          memory: 400Mi
      pulse:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 1
          memory: 400Mi
      aitkwebui:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1
          memory: 200Mi
      configstore:
        requests:
          cpu: 20m
          memory: 100Mi
        limits:
          cpu: 40m
          memory: 128Mi
      orchestrator:
        orchestrator:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 500m
            memory: 600Mi
        celery:
          requests:
            cpu: 100m
            memory: 900Mi
          limits:
            cpu: 1
            memory: 1200Mi
        celerybeat:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 200Mi
      entitlements:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi

  bindings:
    authsvc:
      couchdbInstance: ""
      couchdbInstanceUser: ""
      couchdbUser: ""
      couchdbPassword: ""
      replicas:
    configstore:
      couchdbInstance: ""
      couchdbInstanceUser: ""
      couchdbUser: ""
      couchdbPassword: ""
      replicas:
    entitlements:
      couchdbInstance: ""
      couchdbInstanceUser: ""
      couchdbUser: ""
      couchdbPassword: ""
      replicas:
    shell:
      replicas:
      redis:
    console:
      replicas:
    pulse:
      replicas:
    qproxy:
      replicas:
    iscprofile:
      replicas:
    iscauth:
      couchdbInstance: ""
      couchdbInstanceUser: ""
      couchdbUser: ""
      couchdbPassword: ""
      replicas:
    orchestrator:
      etcd:
      redis:
    aitkwebui:
      replicas:


# IMAGES
  images:
    platform:
      authsvc:
        image: isc-authsvc
        tag: Rel_1.4.0.0_061b790baeb808029daa5334d78490740ce47754_26
      iscprofile:
        image: isc-common-xfeplus-profileservice-ocp
        tag: Rel_1.4.0.0_82a0e0596b4f7f33af6cb7667d66b793771909b6_7607
      iscauth:
        image: isc-common-auth
        tag: Rel_1.4.0.0_82a0e0596b4f7f33af6cb7667d66b793771909b6_7607
      shell:
        image: isc-common-shell
        tag: Rel_1.4.0.0_1bdf690c75bfb69969e9d3b16745fcde006cb4a3_6
      console:
        image: isc-common-console
        tag: Rel_1.4.0.0_9e9d9482352778bae850f919055aa201efc8c7b6_6
      qproxy:
        image: homer-qproxy
        tag: Rel_1.4.0.0_0638dc194ec5e44d1b839bfae6c1db6007070814_55
      pulse:
        image: pulse-dashboard
        tag: Rel_1.4.0.0_db02a9cf1344b9817884b521e9809e30f90861c6_9
      configstore:
        image: isc-common-configstore
        tag: Rel_1.4.0.0_f6c527b67aa1bbb04f9686205a8f6e0b0ec9b335_18
      entitlements:
        image: isc-entitlements
        tag: Rel_1.4.0.0_d3c2f9d0f2d792b2dc94043d5e81226dc3a2f6a6_21
      orchestrator:
        image: isc-aitk-orchestrator
        tag: Rel_1.4.0.0_2a4714e2c2d0fb4a2897a2832f291a4454cc1f5d_116
      aitkwebui:
        image: isc-aitk-webui
        tag: Rel_1.4.0.0_229994b75eef3bf35f316702990196b5bf798831_56
      aitkuds2file:
        image: isc-uds2file
        tag: Rel_1.4.0.0_a6d87dfd76677319dc7d3dd5a303a092acd24189_57
      aitkdefeatureanalysis:
        image: isc-de-feature-analysis
        tag: Rel_1.4.0.0_a6d87dfd76677319dc7d3dd5a303a092acd24189_57
      aitkcommandinterpreter:
        image: command-interpreter
        tag: Rel_1.4.0.0_a6d87dfd76677319dc7d3dd5a303a092acd24189_57
