###############################################################################
# Licensed Materials - Property of IBM.
# Copyright IBM Corporation 2018. All Rights Reserved.
# U.S. Government Users Restricted Rights - Use, duplication or disclosure 
# restricted by GSA ADP Schedule Contract with IBM Corp.
# Contributors:
#  IBM Corporation - initial API and implementation
###############################################################################
bindings:
- name: tiisearch
  debug: false
      
