apiVersion: v2
appVersion: 1.4.0.0
description: Car frontend UI
icon: http://raw.githubusercontent.com/IBM/charts/master/logo/IBM-Security-icon.png
keywords:
- amd64
- Commercial
- ICPRHOCP
- Security
kubeVersion: '>=1.16.0'
name: ibm-isc-car-frontend-ui-prod
version: 1.0.8
