// Add any unique troubleshooting steps here.
Make notes of the the log files that are generated: 
* /ibm/logs/icp4s_install.log - STDOUT of the deployment of Red Hat OpenShift Container Platform using IPI.
* /ibm/logs/cp4s_install_logs.log - STDOUT of the deployment of IBM Cloud Pak for Security including the validation of the installation and deployment of SOAR Entitlement.
* /ibm/logs/bootstrap.log - STDOUT of the high overview of the events during deployment of Red Hat OpenShift Container Platform and IBM Cloud Pak for Security.  

For troubleshooting common Quick Start issues, refer to the https://fwd.aws/rA69w?[AWS Quick Start General Information Guide^] and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation^].

== Resources
// Uncomment section and add links to any external resources that are specified by the partner.
For troubleshooting {partner-product-name} related issues, refer to the https://www.ibm.com/docs/en/SSTDPP_1.9/docs/scp-core/support.html[{partner-product-name} Troubleshooting and Support Guide^].