apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isc-cases-operator
  labels:
    app.kubernetes.io/name: ibm-isc-cases
    app.kubernetes.io/instance: ibm-isc-cases
    app.kubernetes.io/managed-by: ibm-isc-cases
rules:
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
- apiGroups:
    - "route.openshift.io"
  resources:
    - routes
    - routes/custom-host
  verbs:
    - get
    - list
    - create
    - update
    - watch
    - patch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - cases
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - isc-cases-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - isc.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - create
  - patch
  - list
  - watch
  - delete
- apiGroups:
  - crunchydata.com
  resources:
  - pgclusters
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - "rbac.authorization.k8s.io"
  verbs:
  - get
  - create
  - list
  - patch
  - watch
  resources:
  - roles
- apiGroups:
  - ""
  verbs:
  - get
  - list
  resources:
  - pods/log
  resourceNames:
  - "isc-cases-resutil-0"
- apiGroups:
  - ""
  verbs:
  - create
  resources:
  - pods/exec
