kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp4s-pgoperator-pgo-clusterrole
  labels:
    app.kubernetes.io/name: ibm-isc-cases
    app.kubernetes.io/instance: ibm-isc-cases
    app.kubernetes.io/managed-by: ibm-isc-cases
rules:
  # Permissions required by Crunchy PGO
  - verbs:
      - get
      - list
      - create
    apiGroups:
      - '*'
    resources:
      - secrets
  - verbs:
      - get
      - list
    apiGroups:
      - '*'
    resources:
      - nodes
      - pods
      - configmaps
      - storageclasses
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - pgclusters
      - pgpolicies
      - pgtasks
      - pgbackups
      - pgreplicas
      - namespaces
      - roles
      - rolebindings
      - serviceaccounts
  # Permissions to install/uninstall Crunchy PGO
  - verbs:
      - create
      - delete
      - get # required for create_cr
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
  - verbs:
      - create
      - delete
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
  - verbs:
      - delete
    apiGroups:
      - authorization.openshift.io
    resources:
      - clusterroles
      - clusterrolebindings
  - verbs:
      - get
      - create
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
  # Permissions for metrics
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - nodes
      - nodes/metrics
      - pods
  # Permissions to install/uninstall Crunchy PGO required by isc playbook
  - verbs:
      - get
    apiGroups:
      - apps
    resources:
      - deployments
