---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cp4s-pgoperator-pgo-role
  labels:
    app.kubernetes.io/name: ibm-isc-cases
    app.kubernetes.io/instance: ibm-isc-cases
    app.kubernetes.io/managed-by: ibm-isc-cases
rules:
  # Permissions to install/uninstall Crunchy PGO
  - verbs:
      - create
      - update
      - delete
      - list
      - watch
    apiGroups:
      - ""
    resources:
      - serviceaccounts
  - verbs:
      - get
    apiGroups:
      - project.openshift.io
    resources:
      - 'projects'
  - verbs:
      - create
      - delete
    apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
  - verbs:
      - delete
    apiGroups:
      - "authorization.openshift.io"
    resources:
      - roles
      - rolebindings
  # Permissions required by Crunchy PGO
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - pods/log
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - nodes
    verbs: ["get", "deletecollection", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - "*"
  - apiGroups:
      - batch
      - extensions
    resources: ["jobs", "deployments"]
    verbs: ["get", "deletecollection", "list", "watch", "create", "update", "patch", "delete"]
