{{- $rabbitmq := dict "name" "rabbit" "val" . }}
apiVersion: isc.ibm.com/v1
kind: RabbitMQ
metadata:
  name: "{{ template "udi.prefix" $rabbitmq }}"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.global.rabbitmqReplicas }}
  license: true
  base_name: "ibm-rabbitmq-{{ template "udi.prefix" $rabbitmq }}"
  storage_class_name: {{ .Values.global.storageClass | quote }}
  uuid: {{ uuidv4 | quote }}
