{{- $sequenceName := dict "name" "udi" "val" . }}
{{- $udiendpoints := dict "name" "udiendpoints" "val" . }}
{{- $rabbitmq := dict "name" "rabbit" "val" . }}
{{- $minio := dict "name" "minio" "val" . }}
apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: "{{ template "udi.prefix" $udiendpoints }}"
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: udiendpoints install
    operation: generic-install
    service:
      name: "{{ template "udi.prefix" $udiendpoints }}"
      proto: https
      ports:
        - 3000
    {{- include "uds.annotations" . }}
    {{- include "ibm-isc-uds.podcfg" (dict "val" . "app" "udiendpoints") }}
    # dirty hack to deal with scope when using templates
    # see
    # https://github.com/helm/helm/issues/3167#issuecomment-345575993
    # https://github.com/helm/helm/issues/1054#issuecomment-239952250
    # {{$data := dict "Values" .Values.rabbitmq "Chart" .Values.rabbitmq "Release" .Release }}
    env:
      - name: RABBITMQ_SSL
        value: "true"
      - name: RABBITMQ_URL
        value: "ibm-rabbitmq-{{ template "udi.prefix" $rabbitmq }}-svc"
      - name: RABBITMQ_HOST
        value: "ibm-rabbitmq-{{ template "udi.prefix" $rabbitmq }}-svc"
      - name: RABBITMQ_USER
        value: "admin"
      - name: RABBITMQ_PASSWORD
        value: '@refsec/ibm-rabbitmq-{{ template "udi.prefix" $rabbitmq }}-auth-secret/rabbitmq-password'
      - name: ENTITLEMENTS_API
        value: '@inventory/domain/definitions/name'
        format: 'https://{0}/api/entitlements'
      - name: REDIS_HOST
        value: '@inventory/redis/definitions/host'
      - name: REDIS_PASS
        value: '@secret/redis/pass'
      - name: REDIS_PORT
        value: '@inventory/redis/definitions/port'
      - name: REDIS_CERT_PATH
        value: "/etc/config"
      - name: REDIS_UNAME
        value: 'admin'
      - name: REDIS_SENTINEL
        value: 'false'
      - name: REDIS_TLS
        value: 'true'
      - name: "UDS_API_CLIENT_ID"
        value: "@refsec/sysauth-{{ .Values.global.prefix }}/username"
      - name: "UDS_API_CLIENT_SECRET"
        value: "@refsec/sysauth-{{ .Values.global.prefix }}/password"
      - name: "MINIO_ACCESS_KEY_ID"
        value: "@refsec/{{ template "udi.minioPrefix" $minio }}-ibm-minio-creds/accesskey"
      - name: "MINIO_ENDPOINT"
        value: "http://ibm-minio-{{ template "udi.minioPrefix" $minio }}-ibm-minio-svc:9000"
      - name: "MINIO_SECRET_KEY"
        value: "@refsec/{{ template "udi.minioPrefix" $minio }}-ibm-minio-creds/secretkey"
      - name: "AUTHBRIDGE_PUBKEY"
        value: "@refsec/isc-jwt/public"
      - name: "ENTITLEMENTS_PATH"
        value: "/entitlements/v1.0/entitlements/"  
      - name: HTTPS_ENABLED
        value: 'true'
      - name: HTTPS_KEY_PATH
        value: '/etc/config/private.pem'
      - name: HTTPS_CERT_PATH
        value: '/etc/config/public.pem'
      - name: HTTPS_CA_PATH
        value: '/etc/config/ca.crt'
      - name: UDS_ROLES
        value: '[ { \"role\": \"user\", \"permissions\": [ \"canQueryDatasource\", \"canViewResults\" ] }, { \"role\": \"owner\", \"permissions\": [ \"canQueryDatasource\", \"canViewResults\", \"canDeleteDatasource\", \"canUpdateDatasource\"] } ]'
    liveness_probe:
      check: "/bin/true" # /usr/bin/true does not exist in this container, change otherwise
      initialDelaySeconds: 30
      timeoutSeconds: 10
      probeFrequencySeconds: 60
    readiness_probe:
      check: "/bin/true" # /usr/bin/true does not exist in this container, change otherwise
      initialDelaySeconds: 30
      timeoutSeconds: 10
      probeFrequencySeconds: 60
    paths:
      - ingress: /api/{{ template "udi.ingressPrefix" . }}/
        app: /public/
        timeout: 120000
        # noAuth: true # whats this?
