apiVersion: v2
appVersion: 1.4.0.0
description: CSA Adapter service for Cloud Pak for Security
icon: http://raw.githubusercontent.com/IBM/charts/master/logo/ISC-CSAadapter.png
keywords:
- amd64
- Commercial
- ICPRHOCP
- Security
kubeVersion: '>=1.16.0'
name: ibm-isc-csaadapter
version: 1.0.8
