kind: ISCSequence
apiVersion: isc.ibm.com/v1 
metadata:
  name: cp4s-toolbox
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    sort: platform
    instance: default
spec:
  labels:
    generation: {{ uuidv4 | quote }}
  dependencies: []
  actions: 
  - include: cp4s-toolbox
