apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: tiscoordinator
  labels:
    app.kubernetes.io/name: ibm-isc-tiscoordinator
    helm.sh/chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  action:
    name: tiscoordinator install
    operation: generic-install
    service:
      name: tis-coordinator
      proto: https
      ports:
        - 3000
  {{- include "tis.annotations" . }}
  {{- include "ibm-isc-tis.podcfg" (dict "val" . "app" "tiscoordinator" "replicas" 1) }}
    env:
      - name: SERVICE_NAME 
        value: "tis-coordinator"
      - name: API_BASE
        value: "/tis/coordinator"
      - name: APP_FQDN
        value: "@inventory/domain/definitions/name"
      - name: ACCOUNT_CONFIG_DB
        value: "tis-configurations"
      - name: ACCOUNT_REFRESH_CRON
        value: "*/15 * * * *"
      - name: AM_I_AFFECTED_BASE_URL
        value: "https://tis-aia:3000/tis/ami/v2/private"
      - name: AM_I_AFFECTED_CRON_DEFAULT
        value: "0 0 * * *"
      - name: AM_I_AFFECTED_PURGE_CRON_DEFAULT
        value: "0 2 * * *"
      - name: AM_I_AFFECTED_PURGE_DAYS_DEFAULT
        value: 30
      - name: AM_I_AFFECTED_SCAN_TO_CRON_DEFAULT
        value: "*/5 * * * *"
      - name: SCORING_BASE_URL
        value: "https://tis-scoring-controller:3000/tis/scoring/v2"
      - name: SCORING_CRON_DEFAULT
        value: "0 0 * * *"
      - name: API_KEY_URL
        value: "https://isc-auth:3000/apikey"
      - name: CLOUDANT_URL
        value: "@inventory/couch/definitions/url"
      - name: CLOUDANT_USERNAME
        value: "@secret/couch/username"
      - name: CLOUDANT_PASSWORD
        value: "@secret/couch/password"
      - name: SCHEDULE_CALLBACK_BASE_URL
        value: "https://tis-coordinator:3000"
      - name: SCHEDULE_CALLBACK_ENDPOINT
        value: "/tis/coordinator/v2/callback"
      - name: DATA_GATEWAY_URL
        value: "https://tis-data-gateway:3000/tis/gateway"
      - name: XFE_PROXY_URL
        value: "@inventory/domain/definitions/name"
        format: "https://{0}/app/threat-intelligence-insights/"
      - name: DATAGATEWAY_HEALTH_URL
        value: "https://tis-data-gateway:3000/tis/gateway/v2/health"
      - name: CERT_PATH
        value: "/etc/config/ca.crt"
      - name: PUBLIC_KEY_FILE
        value: "/etc/config/jwt.public.pem"
      - name: AUTHBRIDGE_BASE_URL
        value: "https://authsvc:8443"
      - name: TIS_CONNECTOR_MANAGER_PURGE_DAYS_DEFAULT
        value: "90"
      - name: TIS_CONNECTOR_MANAGER_PURGE_JOBS_CRON_DEFAULT
        value: "0 0 * * *"
      - name: TIS_CONNECTOR_MANAGER_BASE_URL
        value: "https://tis-connector-manager:3000/tis/connectors/v1"
      - name: DATA_STORE_URL
        value: "https://tis-data-gateway:3000/tis/gateway/v2/features"
      - name: USE_DATA_GATEWAY
        value: "true"
    liveness_probe:
      path: /tis/coordinator/v2/health/liveness
    readiness_probe:
      path: /tis/coordinator/v2/health/readiness
    paths:
      - ingress: /tis/coordinator
        app: /tis/coordinator
        idle_timeout: 600000
        timeout: 600000
    tempdir: /tmp
