apiVersion: isc.ibm.com/v1
kind: ISCComponent
metadata:
  name: iscprofile
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  action:
    name: iscprofile install
    operation: generic-install
    service:
      name: isc-profile
      proto: https
      ports:
        - 3000
    {{- include "platform.annotate" . }}
    {{- include "ibm-isc-platform.podcfg" (dict "val" . "app" "iscprofile") }}
    env:
      - name: ICP_MASTER_IP
        value: "@inventory/platform/definitions/oidc/tenant"
      - name: ICP_MASTER_PORT
        value: "443"
      - name: IAM_API_KEY
        value: '@refsec/connect-idmgmt-apikey/apikey'
    liveness_probe:
      path: /liveness
    readiness_probe:
      path: /readiness
    paths:
      - ingress: /profileservice/api
        app: /profileservice/api
      - ingress: /api/profileservice/api
        app: /profileservice/api
      - ingress: /api/api/profileservice
        app: /profileservice/api

