apiVersion: isc.ibm.com/v1
kind: ISCSequence
metadata:
  name: iscprofile
  labels:
    sort: iscprofile
    instance: default
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: default
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  labels:
    generation: {{ uuidv4 | quote }}
  dependencies:
     - iscplatform
     - domain-default
  actions: 
    - include: iam-apikey
    - include: iscprofile
    - name: configure couchdb for authsvc
      dependencies:
      - couchdb-authsvc
      operation: couchdb-init
    - include: iscauth
    - name: sync system-auth keys
      operation: system-auth-all
